import { afterEach, expect, it, vi } from 'vitest';
import { subscribePrPolling } from './prPolling.js';
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
it('shares timers, skips hidden windows, avoids overlapping polls and disposes listeners', async () => {
  vi.useFakeTimers();
  const doc = Object.assign(new EventTarget(), { hidden: false });
  const win = new EventTarget();
  vi.stubGlobal('document', doc); vi.stubGlobal('window', win);
  let finish!: () => void;
  const refresh = vi.fn(() => new Promise<void>(resolve => { finish = resolve; }));
  const a = subscribePrPolling('chat', refresh);
  const b = subscribePrPolling('chat', refresh);
  expect(refresh).not.toHaveBeenCalled();
  await vi.advanceTimersByTimeAsync(20_000);
  expect(refresh).toHaveBeenCalledOnce();
  win.dispatchEvent(new Event('focus'));
  await vi.advanceTimersByTimeAsync(20_000);
  expect(refresh).toHaveBeenCalledOnce();
  finish(); await Promise.resolve();
  doc.hidden = true;
  await vi.advanceTimersByTimeAsync(20_000);
  expect(refresh).toHaveBeenCalledOnce();
  doc.hidden = false; doc.dispatchEvent(new Event('visibilitychange'));
  expect(refresh).toHaveBeenCalledTimes(2);
  finish(); await Promise.resolve();
  a(); b();
  win.dispatchEvent(new Event('focus'));
  await vi.advanceTimersByTimeAsync(40_000);
  expect(refresh).toHaveBeenCalledTimes(2);
});
