import { execFileSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { delimiter, join, resolve } from 'node:path';
import type { App } from 'electron';
import { CLI_LINK_FILE, type CliInstallStatus, type CliLink } from '@agent-nekko/shared';

/**
 * Making `agent-nekko` work in a terminal as a consequence of installing the app.
 *
 * The old story was three manual steps: `npm install -g agent-nekko`, then two
 * `export` lines copied out of a settings page, and both of them had to be
 * redone in every new shell. That is a CLI most people never run once. So the
 * app ships the CLI inside itself and does all three:
 *
 *   1. The CLI is bundled as CommonJS (apps/cli/scripts/bundle-app.mjs) and
 *      executed by the app's own Electron binary with ELECTRON_RUN_AS_NODE=1,
 *      so no Node, no npm and no network are involved.
 *   2. A tiny launcher (a `.cmd` on Windows, a `sh` script elsewhere) is
 *      written into a `bin` directory in the user's data dir, and that
 *      directory is put on PATH: `setx` on Windows, a line in the shell
 *      profiles on macOS/Linux.
 *   3. The address and token are written to `cli-link.json`, which the CLI
 *      reads when no flag or env var says otherwise. Env vars couldn't do this
 *      job: they'd mean editing the user's shell profile for a value that
 *      changes whenever the token is rolled, and they'd never reach a terminal
 *      that was already open.
 *
 * Everything here is best-effort and reversible. A failure is reported in the
 * Server tab with the manual fallback (the npm package) still true.
 */

/** Marker so the profile line can be recognised and not written twice. */
const PROFILE_MARKER = '# Added by Agent Nekko (agent-nekko CLI)';

/** Where the bundled CLI ends up, packaged and in development. */
function bundledCliPath(app: Pick<App, 'isPackaged' | 'getAppPath'>): string | null {
  const candidates = app.isPackaged
    ? [join(process.resourcesPath, 'cli', 'agent-nekko-cli.cjs')]
    : [
        resolve(app.getAppPath(), '../../apps/cli/app-dist/agent-nekko-cli.cjs'),
        resolve(app.getAppPath(), '../cli/app-dist/agent-nekko-cli.cjs'),
      ];
  return candidates.find((p) => existsSync(p)) ?? null;
}

/** The directory the launcher goes in: `<userData>/bin`. */
export function cliBinDir(userData: string): string {
  return join(userData, 'bin');
}

/** The launcher's own path, named as the platform expects to find it. */
export function cliBinPath(userData: string): string {
  return join(cliBinDir(userData), process.platform === 'win32' ? 'agent-nekko.cmd' : 'agent-nekko');
}

/**
 * The launcher's contents: run the app's Electron as plain Node on the bundled
 * CLI, passing the user's arguments through.
 *
 * ELECTRON_RUN_AS_NODE is the supported way to borrow the binary's Node; the
 * app's own main process refuses to start under it (see main/index.ts), which
 * is exactly the separation we want.
 */
export function launcherScript(electron: string, cli: string): string {
  if (process.platform === 'win32') {
    return [
      '@echo off',
      'rem Agent Nekko CLI launcher. Regenerated by the app; edits will be lost.',
      'setlocal',
      'set ELECTRON_RUN_AS_NODE=1',
      `"${electron}" "${cli}" %*`,
      'endlocal',
      '',
    ].join('\r\n');
  }
  return [
    '#!/bin/sh',
    '# Agent Nekko CLI launcher. Regenerated by the app; edits will be lost.',
    `ELECTRON_RUN_AS_NODE=1 exec "${electron}" "${cli}" "$@"`,
    '',
  ].join('\n');
}

/** Whether a directory is already on this process's PATH. */
export function dirOnPath(dir: string, pathValue = process.env.PATH ?? ''): boolean {
  const wanted = dir.replace(/[\\/]+$/, '').toLowerCase();
  return pathValue
    .split(delimiter)
    .some((entry) => entry.replace(/[\\/]+$/, '').toLowerCase() === wanted);
}

/**
 * Put the bin dir on PATH for future shells.
 *
 * Windows has an API for this (`setx`, which edits the user's environment and
 * broadcasts the change). Unix does not, so the honest thing is a marked line
 * appended to the shell profiles that exist, which the user can see and delete.
 * Neither affects a shell that is already open; the caller says so.
 */
function persistPath(binDir: string): { changed: boolean; message?: string } {
  if (process.platform === 'win32') {
    if (dirOnPath(binDir, process.env.PATH ?? '')) return { changed: false };
    // Append to the *user* PATH only, read from the user's own environment.
    // `setx PATH %PATH%` is the well-known wrong way: this process's PATH is
    // the system and user entries merged, so it copies the whole system PATH
    // into the user one, and setx truncates at 1024 characters on top. The
    // .NET call has no length limit and broadcasts the change to new shells.
    // The folder travels as an env var so no quoting of a path is involved.
    const script = [
      "$dir = $env:NEKKO_BIN_DIR",
      "$cur = [Environment]::GetEnvironmentVariable('Path', 'User')",
      "$parts = @(); if ($cur) { $parts = $cur -split ';' | Where-Object { $_ } }",
      "if ($parts | Where-Object { $_.TrimEnd('\\') -ieq $dir.TrimEnd('\\') }) { 'present'; exit 0 }",
      "[Environment]::SetEnvironmentVariable('Path', (($parts + $dir) -join ';'), 'User')",
      "'added'",
    ].join('; ');
    try {
      const out = execFileSync('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', script], {
        env: { ...process.env, NEKKO_BIN_DIR: binDir },
        timeout: 15_000,
        windowsHide: true,
        encoding: 'utf8',
      });
      return { changed: out.trim() === 'added' };
    } catch {
      return { changed: false, message: 'Could not update your PATH. Add the folder above to it by hand.' };
    }
  }

  const home = process.env.HOME;
  if (!home) return { changed: false, message: 'No home directory to add a PATH line to.' };
  const line = `${PROFILE_MARKER}\nexport PATH="${binDir}:$PATH"\n`;
  let changed = false;
  for (const name of ['.zshrc', '.bashrc', '.profile']) {
    const file = join(home, name);
    if (!existsSync(file)) continue;
    try {
      const body = readFileSync(file, 'utf8');
      if (body.includes(PROFILE_MARKER)) continue;
      writeFileSync(file, `${body.replace(/\s*$/, '')}\n\n${line}`, 'utf8');
      changed = true;
    } catch {
      /* someone else's file; a failure here is not fatal */
    }
  }
  if (!changed && !existsSync(join(home, '.zshrc')) && !existsSync(join(home, '.bashrc'))) {
    try {
      writeFileSync(join(home, '.profile'), `${line}`, { flag: 'a' });
      changed = true;
    } catch {
      return { changed: false, message: 'Could not write a shell profile. Add the folder above to your PATH.' };
    }
  }
  return { changed };
}

/**
 * Write the launcher and make sure its directory is on PATH. Idempotent: the
 * launcher is rewritten every time (it names absolute paths that move when the
 * app updates) and PATH is only touched when it is actually missing.
 */
export function installCli(
  app: Pick<App, 'isPackaged' | 'getAppPath' | 'getPath'>,
  opts: { path?: boolean } = {},
): CliInstallStatus {
  const userData = app.getPath('userData');
  const binDir = cliBinDir(userData);
  const binPath = cliBinPath(userData);
  const cli = bundledCliPath(app);

  if (!cli) {
    return {
      available: true,
      installed: false,
      onPath: false,
      binDir,
      command: 'agent-nekko',
      message:
        'This build does not include the CLI. Install it from npm instead: npm install -g agent-nekko',
    };
  }

  try {
    mkdirSync(binDir, { recursive: true });
    writeFileSync(binPath, launcherScript(process.execPath, cli), 'utf8');
    if (process.platform !== 'win32') chmodSync(binPath, 0o755);
  } catch (e) {
    return {
      available: true,
      installed: false,
      onPath: false,
      binDir,
      command: 'agent-nekko',
      message: `Could not write the launcher: ${(e as Error).message}`,
    };
  }

  const already = dirOnPath(binDir);
  const persisted = already || opts.path === false ? { changed: false } : persistPath(binDir);

  return {
    available: true,
    installed: true,
    onPath: already,
    needsRestart: !already && persisted.changed,
    binPath,
    binDir,
    // Until PATH takes effect, the full path is the command that actually
    // works, and it is better to show that than one that errors.
    command: already ? 'agent-nekko' : binPath,
    message: persisted.message,
  };
}

/** Report the state without writing anything (what the Server tab polls). */
export function cliInstallStatus(app: Pick<App, 'isPackaged' | 'getAppPath' | 'getPath'>): CliInstallStatus {
  const userData = app.getPath('userData');
  const binDir = cliBinDir(userData);
  const binPath = cliBinPath(userData);
  const installed = existsSync(binPath);
  const onPath = dirOnPath(binDir);
  return {
    available: true,
    installed,
    onPath,
    binPath: installed ? binPath : undefined,
    binDir,
    command: installed && !onPath ? binPath : 'agent-nekko',
    message: bundledCliPath(app)
      ? undefined
      : 'This build does not include the CLI. Install it from npm instead: npm install -g agent-nekko',
  };
}

/**
 * Write (or clear) the address and token the CLI should use by default.
 *
 * Called on every server settings change, so rolling the token or moving the
 * port keeps working terminals working. The file is written `0600`: it carries
 * a bearer token for an endpoint that can run shell commands.
 */
export function writeCliLink(dataDir: string, link: CliLink): void {
  try {
    mkdirSync(dataDir, { recursive: true });
    const file = join(dataDir, CLI_LINK_FILE);
    writeFileSync(file, JSON.stringify(link, null, 2), { encoding: 'utf8', mode: 0o600 });
    chmodSync(file, 0o600);
  } catch {
    /* The CLI falls back to the local data directory; not worth an error box. */
  }
}
